@echo off

REM default is the android openmw.cfg as well as the omwllf and delta folders
REM all reside in the same folder as this batch file, but you can modify it
REM all, by default the android openmw.cfg will be in
REM /sdcard/omw_nightly/config

REM note: this batch file assumes all folders exist and contain the right
REM files, all .cfg and .omwaddon files will be overwritten without prompt so
REM make sure to enable backup by setting this value to 1
set "backup=1"

REM set value to 1 to add a date and time stamp to the end of the file name for
REM both the omwllf and delta output files, added before the extension, if you
REM are located in the States change value of American to 1 to adjust date
set "stamp="
set "american="

REM set value to 1 to run omwllf.py and delta_plugin.exe in silent mode,
REM neither will output anything to screen including errors, but this batch
REM file will still output to screen
set "silent=1"

REM location of android version of openmw.cfg on windows, can be a folder, if
REM file name not provided then openmw.cfg will be used, if left blank will
REM assume file name is openmw.cfg and located in the same folder as this
REM batch file
set "input="

REM location of windows version of openmw.cfg, both omwllf and delta will look
REM for the converted openmw.cfg here by default so its best to leave this
REM blank, will output to folder or name below if you want to override default
set "output="

REM location of Data Files folder on android, must match paths in openmw.cfg,
REM use /sdcard instead of /storage/emulated/0, no default value
set "folderData=/sdcard/Download/openmw/Morrowind/Data Files"

REM location of Data Files folder on windows, must already contain all base
REM game and expansion .bsa and .esm files, no default value
set "replaceData=D:\Morrowind\Data Files"

REM location of Mods folder on android, must match paths in openmw.cfg, use
REM /sdcard instead of /storage/emulated/0, no default value
set "folderMod=/sdcard/Download/openmw/Morrowind/Mod Files"

REM location of Mods folder on windows, must already contain all mods from the
REM android openmw.cfg in the same folder structure, including all .esm and
REM .esp files, no default value
set "replaceMod=D:\Morrowind\Mod Files"

REM name of folder for omwaddon files generated by omwllf and delta on windows,
REM has to match android openmw.cfg and must be inside Mods folder, can include
REM subfolders, if the omwaddon files are in the base Mods folder then just
REM leave blank
set "omwaddonFolder=LAST"

REM location of omwllf.py, can be relative or absolute path
set "omwllfDir=omwllf-master"

REM name of .omwaddon file generated by omwllf.py, outputs to omwaddonFolder,
REM file extension can be omitted but name must match name in android
REM openmw.cfg
set "omwllfOut=omwllf.omwaddon"

REM location of delta_plugin.exe, can be relative or absolute path
set "deltaDir=delta-plugin-0.17.1-windows-amd64"

REM name of .omwaddon file generated by delta_plugin.exe, outputs to
REM omwaddonFolder, file extension can be omitted but name must match name in
REM android openmw.cfg
set "deltaOut=delta.omwaddon"

setlocal enabledelayedexpansion

if "%input%" == "" set input=openmw.cfg
if not "%replaceMod:~-1%" == "\" set replaceMod=%replaceMod%\
if "%omwaddonFolder%" == "" set omwaddonFolder=/
if "%omwaddonFolder:~0,1%" == "\" set omwaddonFolder=%omwaddonFolder:~1%
if "%omwaddonFolder:~-1%" == "\" set omwaddonFolder=%omwaddonFolder:~0,-1%

if not "%input:~-4%" == ".cfg" set input=%input%\openmw.cfg
if not exist !input! (
	echo ^>^>^>^> !input! not found at expected location
	echo:
	pause & goto :eof
)

echo ^>^>^>^> !input! found
echo:

if not "%folderData:~0,1%" == "/" set folderData=/%folderData%
if not "%folderMod:~0,1%" == "/" set folderMod=/%folderMod%
if not "%folderMod:~-1%" == "/" set folderMod=%folderMod%/
set omwComb=%folderMod%%omwaddonFolder%
set addonComb=%replaceMod%%omwaddonFolder%
if not exist !addonComb! (
	echo ^>^>^>^> !addonComb! not found at expected location
	echo:
	pause & goto :eof
)

if "%output%" == "" set output=%userprofile%\documents\my games\openmw
if not "%output:~-4%" == ".cfg" set output=%output%\openmw.cfg

if "%backup%" == "1" (
	if exist "%output%" (
		copy "%output%" "%output%.bak" > NUL
		echo ^>^>^>^> backed up %output%
		echo:
	)
)

if "%omwllfOut:.omwaddon=%" == "%omwllfOut%" set omwllfOut=%omwllfOut%.omwaddon
if "%deltaOut:.omwaddon=%" == "%deltaOut%" set deltaOut=%deltaOut%.omwaddon

for /f "delims=" %%i in ('type "!input!" ^& break ^> "!output!" ') do (
	set "line=%%i"
	if not "!line:%omwComb%=!" == "!line!" set line=#
	if not "!line:%omwllfOut%=!" == "!line!" set line=#
	if not "!line:%deltaOut%=!" == "!line!" set line=#
	set replace=!line:%folderData%=%replaceData%!
	set replace=!replace:%folderMod%=%replaceMod%!
	>> "!output!" echo !replace!
)

echo ^>^>^>^> finished converting !output!
echo:

if not "%omwllfDir:omwllf.py=%" == "%omwllfDir%" ^
	set omwllfDir=%omwllfDir:omwllf.py=%
if not "%deltaDir:delta_plugin.exe=%" == "%deltaDir%" ^
	set deltaDir=%deltaDir:delta_plugin.exe=%

for %%i in (%omwllfDir% %deltaDir%) do (
	if not exist %%i (
		echo ^>^>^>^> %%i not found at expected location
		echo:
		pause & goto :eof
	)
)

if "%stamp%" == "1" (
	set omwllfOut=%omwllfOut:.omwaddon=%
	set deltaOut=%deltaOut:.omwaddon=%
	if "%american%" == "1" (
		set datetime=%date:~6,4%%date:~0,2%%date:~3,2%-%time:~0,2%%time:~3,2%%time:~6,2%
	) else (
		set datetime=%date:~6,4%%date:~3,2%%date:~0,2%-%time:~0,2%%time:~3,2%%time:~6,2%
	)
	set omwllfOut=!omwllfOut!-!datetime!.omwaddon
	set deltaOut=!deltaOut!-!datetime!.omwaddon
)

set newDir=%replaceMod:"=%\%omwaddonFolder:"=%
set returnDir=%cd%

if "%backup%" == "1" (
	pushd %newDir%
	if exist %omwllfOut% (
		copy %omwllfOut% %omwllfOut%.bak > NUL
		echo ^>^>^>^> backed up %omwllfOut%
		echo:
	)
	popd
)

echo ^>^>^>^> running omwllf.py
echo:
pushd %omwllfDir%
if "%silent%" == "1" (
	python omwllf.py -m %omwllfOut% -d ^"%newDir%^" > NUL
) else (
	python omwllf.py -m %omwllfOut% -d ^"%newDir%^"
)
if %errorlevel% == 1 (
	echo:
	echo ^>^>^>^> error returned by omwllf
	echo:
	pause & goto :eof
)
echo ^>^>^>^> %omwllfOut% written to %addonComb%
echo:

if "%backup%" == "1" (
	pushd %newDir%
	if exist %deltaOut% (
		copy %deltaOut% %deltaOut%.bak > NUL
		echo ^>^>^>^> backed up %deltaOut%
		echo:
	)
	popd
)

echo ^>^>^>^> running delta_plugin.exe
echo:
cd %returnDir% & cd %deltaDir%
if "%silent%" == "1" (
	delta_plugin -q merge ^"%newDir%\%deltaOut%^" > NUL
) else (
	delta_plugin merge ^"%newDir%\%deltaOut%^"
)

if %errorlevel% == 1 (
	echo:
	echo ^>^>^>^> error returned by delta-plugin
	echo:
	pause & goto :eof
)
echo:
echo ^>^>^>^> %deltaOut% written to %addonComb%

echo:
echo ^>^>^>^> process finished
echo:
cd %returnDir% & pause
